//! Turn `src/web/vendor/` into a table the binary can serve, so nothing has one route per file.
//!
//! Four vendored scripts became four `include_str!` constants and four handlers, and a build step
//! produces a directory whose file *names* carry content hashes — so neither the count nor the names
//! are known when the code is written. A table generated from the directory is the only shape that
//! serves both, and it keeps the property the hand-written constants had: skein is one binary that
//! cannot be half-upgraded.
//!
//! Bytes, not strings. A stylesheet is text and a font is not, and `include_str!` is a decision that
//! the asset layer is text-only — which it stops being the moment a build emits one image.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    let dir = Path::new("src/web/vendor");
    // Without this, adding a file to the directory does not rebuild the table that lists it — the
    // asset would simply not exist, with nothing said.
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut names: Vec<String> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", dir.display()))
        .flatten()
        .filter(|e| e.path().is_file())
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .collect();
    // Sorted, so the generated file is the same for the same directory and a rebuild is not a diff.
    names.sort();

    let mut out = String::from(
        "// Generated by build.rs from src/web/vendor. Do not edit.\n\
         pub static EMBEDDED: &[(&str, &[u8])] = &[\n",
    );
    for name in &names {
        println!("cargo:rerun-if-changed={}", dir.join(name).display());
        let path = std::fs::canonicalize(dir.join(name)).expect("canonicalize an asset");
        writeln!(
            out,
            "    ({name:?}, include_bytes!({:?})),",
            path.to_string_lossy()
        )
        .unwrap();
    }
    out.push_str("];\n");

    let target = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("assets.rs");
    std::fs::write(&target, out).unwrap_or_else(|e| panic!("write {}: {e}", target.display()));
}
