// Turn `cockpit/src/*.mjs` into the one bundle the page loads.
//
// **No dependency, and that is the point rather than an economy.** The cockpit is served from a
// binary to a browser on the same machine and has no business fetching from a CDN — the same reason
// `xterm` and `marked` are vendored — and a build step for five leaf functions that needed a package
// tree would cost more trust than it bought.
//
// **It refuses a module with an `import` in it.** That is the design constraint the modules keep:
// what belongs here is leaf functions, all inputs as arguments, no module state, no DOM — exactly
// the set §13's pure-function law is about. Concatenation is only correct for those, so the build
// checks rather than assumes; a module that grew a dependency fails the build instead of producing a
// bundle whose behaviour differs from the modules the tests import.
//
//   node cockpit/build.mjs           rewrite the bundle
//   node cockpit/build.mjs --check   fail if the committed bundle is stale

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, "src");
const bundle = join(here, "..", "src", "web", "vendor", "cockpit.js");

export function build() {
  // Sorted, so the same directory always produces the same bytes and a rebuild is not a diff.
  const names = readdirSync(src).filter(f => f.endsWith(".mjs")).sort();
  const parts = [
    "// Generated by cockpit/build.mjs from cockpit/src. Do not edit.",
    "//",
    "// These are the cockpit's pure functions, tested in node — see cockpit/README.md. They are",
    "// globals here because the page is one classic script; they are modules there because a",
    "// function that cannot be imported cannot be tested except by reimplementing it, and a",
    "// reimplementation agrees with the code right up until one of them changes.",
    "",
  ];
  for (const name of names) {
    const text = readFileSync(join(src, name), "utf8");
    if (/^\s*import\s/m.test(text)) {
      throw new Error(
        `${name} has an import. These modules are concatenated into one script, so only leaf ` +
          `functions belong here — take the dependency as an argument, or leave the function in the page.`
      );
    }
    parts.push(`// ── ${name} ──`);
    // `export` is how the tests reach them and is meaningless in a classic script; dropping the
    // keyword is the whole of the transform, which is why it is safe to do with a regex.
    parts.push(text.replace(/^export\s+/gm, "").trimEnd());
    parts.push("");
  }
  return parts.join("\n") + "\n";
}

const built = build();
if (process.argv.includes("--check")) {
  const committed = readFileSync(bundle, "utf8");
  if (committed !== built) {
    console.error(
      "cockpit/src has changed and src/web/vendor/cockpit.js has not.\n" +
        "The binary embeds the bundle and `cargo build` does not run node, so a stale one is a\n" +
        "cockpit quietly running last week's code. Fix: node cockpit/build.mjs"
    );
    process.exit(1);
  }
  console.log("the cockpit bundle is what cockpit/src builds");
} else {
  writeFileSync(bundle, built);
  console.log(`wrote ${bundle}`);
}
